exports.API_REQUEST_INITIATED = 'API_REQUEST_INITIATED';
exports.API_REQUEST = 'API_REQUEST';
exports.API_RESPONSE_RECEIVED = 'API_RESPONSE_RECEIVED';

exports.INCREMENT = 'INCREMENT';
exports.DECREMENT = 'DECREMENT';

exports.WSOCKET = 'WSOCKET';

exports.CHANGE_TAB = 'CHANGE_TAB';

exports.TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
